version: "3"

services:
#  lb3:
#    image: haproxy:alpine
#    ports:
#      - 82:80
#    volumes:
#      - "./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg"
#    depends_on:
#      - service1
#      - service2
#  lb2:
#    image: nginx:alpine
#    ports:
#      - 81:80
#    volumes:
#      - "./default.conf:/etc/nginx/conf.d/default.conf"
#    depends_on:
#      - service1
#      - service2
  lb1:
    image: traefik:2.4
    ports:
      - 80:80
    volumes:
      - "./traefik.toml:/traefik.toml"
      - "./traefik_dynamic.toml:/traefik_dynamic.toml"
    depends_on:
      - service
    networks:
      - internal
      - external
  service:
    build: .
    networks:
      - internal
  db:
    image: postgres:13-alpine
    volumes:
      - ./.db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=mydb
    networks:
      - internal

networks:
  external:
  internal:
    internal: true
