version: "3"

services:
  lb3:
    image: haproxy:alpine
    ports:
      - 83:80
    volumes:
      - "./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg"
    depends_on:
      - service1
      - service2
  lb2:
    image: nginx:alpine
    ports:
      - 82:80
    volumes:
      - "./default.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      - service1
      - service2
  lb1:
    image: traefik:2.4
    ports:
      - 8080:8080
      - 80:80
    volumes:
      - "./traefik.toml:/traefik.toml"
      - "./traefik_dynamic.toml:/traefik_dynamic.toml"
    depends_on:
      - service1
      - service2
  service1:
    image: caddy:2-alpine
#    ports:
#      - 81:80
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./service1.html:/static/index.html
  service2:
    image: caddy:2-alpine
#    ports:
#      - 82:80
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./service2.html:/static/index.html
#  db:
#    image: postgres:13-alpine
#    volumes:
#      - ./.db:/var/lib/postgresql/data
#    ports:
#      - 5432:5432
#    environment:
#      - POSTGRES_PASSWORD=password
#      - POSTGRES_USER=postgres
#      - POSTGRES_DB=mydb
